baseurl = "https://tanducmai.com"
theme = "coder-portfolio"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "tan-duc-mai" # Enable or disable Disqus.

[params] # theme parameters
    avatarurl = "images/avatar.svg" # Contain the path of the optionnal avatar in the static folder.

    # footercontent = "Thanks for reading! -> Please click on an icon to share" # Add footer content
    # fixedbarContent = "Please share it if you like it → " # Add fixedbar content
    # fixedbarContentAfter = "Thank you! Please choose which platform to share →" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    # snsShare = false            # new add
    # Popular sns share
    # if you want add sns. please message!
    # enableTwitterShare = true  # new add
    # enableFacebookShare = true # new add
    # enableHatenaShare = false  # new add
    # enableLineShare = false    # new add
    # enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
# [[params.social]]
#     name = "Github"
#     icon = "fab fa-github"
#     weight = 1
#     url = "https://github.com/tanducmai/"
# [[params.social]]
#     name = "Facebook"
#     icon = "fab fa-facebook"
#     weight = 2
#     url = "https://facebook.com/henry.mai.372/"
# [[params.social]]
#     name = "LinkedIn"
#     icon = "fab fa-linkedin"
#     weight = 3
#     url = "https://www.linkedin.com/in/tanducmai/"

[param]
    langseparator = "|" # separates menus from language selectors.

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Tan Duc Mai"

        # You can configure the theme parameter for each language. 
        [languages.en.params]
        author = "Tan Duc Mai"
        info = "Python Developer"
        description = "My Programming Portfolio and Personal Website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "about"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2.0
        url = "posts"

        [[languages.en.menu.main]]
        name = "Portfolio"
        weight = 2.0
        url = "projects"


    [languages.ja]
        languagename = "Japanese"
        title = "ヘンリ マイ"

        [languages.ja.params]
            author = "ヘンリ マイ"
            description = "石見 優丞のサイト"
            keywords = "blog,developer, ブログ, エンジニア"
            info = "PYTHON エンジニア"

        [languages.ja.menu]

            [[languages.ja.menu.main]]
            name = "わたし"
            weight = 1.0
            url = "ja/about"

            # [[languages.ja.menu.main]]
            # name = "ブログ"
            # weight = 2.0
            # url = "ja/posts"

            # [[languages.ja.menu.main]]
            # name = "プロジェクト"
            # weight = 2.0
            # url = "ja/projects"
